// <auto-generated />
using System;
using EmployeeInformation.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeInformation.EF.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20221103061019_mig_2")]
    partial class mig_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.DepartmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Askerlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaslamaTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalismaSuresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentDTOId")
                        .HasColumnType("int");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EgitimDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IseGiris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstenCikis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedeniDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentDTOId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2018_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2018_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2018_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2018");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2019DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2019_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2019_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2019_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2019");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2020DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2020_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2020_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2020_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2020");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2021DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2021_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2021_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2021_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2021");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2022DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2022_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2022_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2022_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2022");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2023DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Agustos2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Aralik2023_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ekim2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ekim2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Eylul2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Haziran2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Kasim2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mart2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Mayis2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Nisan2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Ocak2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Subat2023_C6")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C1")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C2")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C3")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C4")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C5")
                        .HasColumnType("int");

                    b.Property<int>("Temmuz2023_C6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations2023");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.DepartmentDTO", "DepartmentDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("DepartmentDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2018DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2018DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2019DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2019DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2019DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2020DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2020DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2020DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2021DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2021DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2021DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2022DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2022DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2022DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2023DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2023DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2023DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.DepartmentDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Navigation("Vacation2018DTO")
                        .IsRequired();

                    b.Navigation("Vacation2019DTO")
                        .IsRequired();

                    b.Navigation("Vacation2020DTO")
                        .IsRequired();

                    b.Navigation("Vacation2021DTO")
                        .IsRequired();

                    b.Navigation("Vacation2022DTO")
                        .IsRequired();

                    b.Navigation("Vacation2023DTO")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
