// <auto-generated />
using System;
using EmployeeInformation.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeInformation.EF.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20221124071331_mig_1")]
    partial class mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.DepartmentDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.EducationDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EducationStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Educations");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.MaritialDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaritialStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maritials");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.MilitaryServiceDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MilitaryStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MilitaryServices");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.SectorDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Askerlik")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaslamaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("CalismaSuresi")
                        .HasColumnType("TEXT");

                    b.Property<string>("CepTel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EducationDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EgitimDurumu")
                        .HasColumnType("TEXT");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fotograf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gorev")
                        .HasColumnType("TEXT");

                    b.Property<string>("IseGiris")
                        .HasColumnType("TEXT");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IstenCikis")
                        .HasColumnType("TEXT");

                    b.Property<string>("Maas")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaritialDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MedeniDurum")
                        .HasColumnType("TEXT");

                    b.Property<int>("MilitaryServiceDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectorDTOId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TCKimlik")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentDTOId");

                    b.HasIndex("EducationDTOId");

                    b.HasIndex("MaritialDTOId");

                    b.HasIndex("MilitaryServiceDTOId");

                    b.HasIndex("SectorDTOId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2018_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2018");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2019DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2019_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2019");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2020DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2020_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2020");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2021DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2021_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2021");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2022DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2022_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2022");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2023DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Agustos2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Aralik2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ekim2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ekim2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eylul2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haziran2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kasim2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mart2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mayis2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nisan2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ocak2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Subat2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temmuz2023_C6")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vacations2023");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.Common.DepartmentDTO", "DepartmentDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("DepartmentDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeInformation.EF.DTOs.Common.EducationDTO", "EducationDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("EducationDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeInformation.EF.DTOs.Common.MaritialDTO", "MaritialDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("MaritialDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeInformation.EF.DTOs.Common.MilitaryServiceDTO", "MilitaryServiceDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("MilitaryServiceDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeInformation.EF.DTOs.Common.SectorDTO", "SectorDTO")
                        .WithMany("EmployeeDTOs")
                        .HasForeignKey("SectorDTOId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartmentDTO");

                    b.Navigation("EducationDTO");

                    b.Navigation("MaritialDTO");

                    b.Navigation("MilitaryServiceDTO");

                    b.Navigation("SectorDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2018DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2018DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2019DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2019DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2019DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2020DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2020DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2020DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2021DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2021DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2021DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2022DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2022DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2022DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2023DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2023DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2023DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.DepartmentDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.EducationDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.MaritialDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.MilitaryServiceDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Common.SectorDTO", b =>
                {
                    b.Navigation("EmployeeDTOs");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Navigation("Vacation2018DTO")
                        .IsRequired();

                    b.Navigation("Vacation2019DTO")
                        .IsRequired();

                    b.Navigation("Vacation2020DTO")
                        .IsRequired();

                    b.Navigation("Vacation2021DTO")
                        .IsRequired();

                    b.Navigation("Vacation2022DTO")
                        .IsRequired();

                    b.Navigation("Vacation2023DTO")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
