// <auto-generated />
using System;
using EmployeeInformation.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeInformation.EF.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20221025112628_mig_3")]
    partial class mig_3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Askerlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BaslamaTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalismaSuresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CepTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogumTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Durum")
                        .HasColumnType("bit");

                    b.Property<string>("EgitimDurumu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBilgi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fotograf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gorev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IseGiris")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IstenCikis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Maas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedeniDurum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TCKimlik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ocak2018_c1")
                        .HasColumnType("int");

                    b.Property<int?>("Ocak2018_c2")
                        .HasColumnType("int");

                    b.Property<int?>("Ocak2018_c3")
                        .HasColumnType("int");

                    b.Property<int?>("Ocak2018_c4")
                        .HasColumnType("int");

                    b.Property<int?>("Ocak2018_c5")
                        .HasColumnType("int");

                    b.Property<int?>("Ocak2018_c6")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c1")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c2")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c3")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c4")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c5")
                        .HasColumnType("int");

                    b.Property<int?>("Subat2018_c6")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Vacations");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.Vacation2018DTO", b =>
                {
                    b.HasOne("EmployeeInformation.EF.DTOs.EmployeeDTO", "EmployeeDTO")
                        .WithOne("Vacation2018DTO")
                        .HasForeignKey("EmployeeInformation.EF.DTOs.Vacation2018DTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeDTO");
                });

            modelBuilder.Entity("EmployeeInformation.EF.DTOs.EmployeeDTO", b =>
                {
                    b.Navigation("Vacation2018DTO")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
